# Use Java 17
FROM openjdk:17-jdk-slim

# Set the working directory inside the container
WORKDIR /app

# Copy everything to the container
COPY . .

# Build the project (skip tests to make it faster)
RUN ./mvnw clean package -DskipTests

# Expose port 8080 (Spring Boot default)
EXPOSE 8080

# Run the built jar file (update the name if needed)
CMD ["java", "-jar", "target/librarymanagement-0.0.1-SNAPSHOT.jar"]
